# Salon Service Configuration V0.0.1
# file to store ALL application configuration properties
# all props can be overridden by injecting Java Environment Variables
#   capitalize config property and replace periods and hyphens with underscores
#   ex. server.port (spring environment) can be overridden by setting SERVER_PORT

application:
  title: @project.name@
  version: @project.version@

server:
  # service will be available on this port
  port: 8080
  cache: ./localfilecache/

spring:
  banner.location: classpath:banner.txt
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

mysql:
  protocol: jdbc:mysql
  hostname: localhost
  port: 3306
  database: dev_dynasty_salon
  username: dev_dynasty_service
  password: password

aws:
  s3:
    bucket: circlesdevocean
    apppath: eecs447/local/
