# file to store ALL application configuration properties

server:
  # service will be available on this port
  port: 8080

mysql:
  scheme: jdbc:mysql
  path: localhost
  port: 3306
  database:
    name: project
    username: eecs447
    password: password