# file to store ALL application configuration properties
# all props can be overridden by injecting Java Environment Variables
#   capitalize config property and replace periods and hyphens with underscores
#   ex. server.port (spring environment) can be overridden by setting SERVER_PORT

server:
  # service will be available on this port
  port: 8080
  cache: ./localfilecache/

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

mysql:
  protocol: jdbc:mysql
  hostname: localhost
  port: 3306
  database: project
  username: eecs447
  password: password

aws:
  s3:
    bucket: circlesdevocean
    apppath: eecs447/local/

#logging:
#  level:
#    root: ERROR
#    org.morriswa.eecs447: INFO
##    org.springframework.data.repository: OFF
##    org.springframework.beans.factory: OFF
##    org.springframework.boot.SpringApplication: OFF
##    org.springframework.boot.web.servlet.context: OFF
##    org.apache.catalina.core: OFF
##    com.zaxxer.hikari: OFF
