# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

#
# AUTHOR: William A. Morris
# CREATION_DATE: 2024-01-19
# PURPOSE:
#   whenever new code is pushed to the main branch, this file will execute the following steps
#   in order to publish this application as a Docker Container on Dockerhub
#   - run unit tests
#   - build the project and create a Java ARchive (JAR)
#   - create Docker Container from generated application artifacts
#   - publish container

name: Test, Build, Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven

    - name: Build App and Run Unit Tests with Maven
      run: |
        mvn -B package --file pom.xml 
        mkdir ~/output 
        cp -a target/. ~/output/target/
        cp Dockerfile ~/output/
        
    - name: Extract project version
      run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
      id: project

    - name: Confirm Correct Version
      run: echo ${{ format('Attempting to Publish Version eecs447-project-service:{0}', steps.project.outputs.version) }}

    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: morriswa
        password: ${{ secrets.DOCKERPASSWORD }}
      
    - name: Build and Publish to Docker Hub
      run: |
        cd ~/output
        docker build . -t morriswa/eecs447-project-service:${{ steps.project.outputs.version }}
        docker push morriswa/eecs447-project-service:${{ steps.project.outputs.version }}
